# Generated by Django 2.1.5 on 2022-06-06 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_auto_20220603_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_file',
            new_name='bookfile',
        ),
    ]
